### ISSUE TITLE
VitaDeploy got replaced by near.

### ISSUE THREAD

**Issue by Baycats** [SKGleba/henlo_jb#4]
Replaced Near with VitaDeploy, after a restart, it reverted.
Unsafe Homebrew is ON

**Comment by SKGleba** [comment]
Did it exit with a success message? Retry.
If you have access to a file manager, check if vs0:app/NPXS10000/ contains a near_backup folder

**Comment by Baycats** [comment]
Sorry not after a restart, i downgraded then vitadeploy got replaced with near.

**Comment by Baycats** [comment]
Im also on a JP import, if that helps.

**Comment by SKGleba** [comment]
Yeah, downgrading/upgrading the system software installs a new system partition image - so any modifications are gone.
If you do not have an external or internal memory card you can disable version spoofing in henkaku settings and use deploy.psp2.dev to replace near again.
Then i recommend adding an internal memory card using this guide: https://guide.psp2.dev/guides/creating-an-internal-memory-card
