### ISSUE TITLE
[Feature Request] 3.60 Support

### ISSUE THREAD

**Issue by JazzMartian** [SKGleba/henlo_jb#5]
This may be a long shot of a request, but I hope you will consider it. I've read that there are a small number of apps and plugins that either run exclusively on 3.60, or perform ideally on it.

**Comment by SKGleba** [comment]
from a quick look it looks like the heap layout is different.
i already got all offsets and gadgets so only thats left
but i probably wont do it, no time nor will to work on 3.60

**Comment by JazzMartian** [comment]
Understandable, have a nice day. ✌
